export const recipes = [
    {
        id: 0,
        idUser: 0,
        author: 'Julia de Carvalho',
        img: 'https://s2.glbimg.com/Lna-moWP46oqPm5QRbzO9imvbDY=/0x0:547x348/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2020/k/u/Fc2LJRT3iDt0m76OI9xg/bolo-de-fuba-cremoso.png',
        name_recipe: 'Receita de bolo de fubá cremoso',
        category: 'Bolos e doces',
        nmr_hearts: 18,
        nmr_eyes: 98,
        votes: [1, 7, 16, 25, 29],
        time: 45,
        ing: 5,
        comments: [
            {
                idUser: 0,
                ask: "Vocẽ usou cenoura nesse bolo?",
                answer: ''
            },
            {
                idUser: 1,
                ask: "Esse bolo é de comer?",
                answer: 'acho que sim.'
            }
        ],
        createdAt: new Date(2023, 1, 14, 12, 42, 0),
    },
    {
        id: 1,
        idUser: 2,
        img: 'https://img.itdg.com.br/tdg/images/recipes/000/000/770/323683/323683_original.jpg',
        category: 'Comida caseira',
        name_recipe: 'Arroz soltinho',
        author: 'Caique de Carvalho',
        nmr_hearts: 29,
        nmr_eyes: 53,
        votes: [6, 15, 24, 28],
        time: 15,
        ing: 3,
        comments: [
            {
                idUser: 0,
                ask: "Azeite de olivia ou azeite extra virgem que você usou?",
                answer: "usei azeite de oliva"
            }
        ],
        createdAt: new Date(2022, 12, 11, 11,23,10),
    },
    {
        id: 2,
        idUser: 1,
        img: 'https://www.padariavicosa.com.br/content/images/thumbs/0000070_pao-com-manteiga-na-canoa_800.jpeg',
        category: 'Café da manhã',
        name_recipe: 'Pão com manteiga',
        author: 'Guilherme Phellipe',
        nmr_hearts: 18,
        nmr_eyes: 67,
        votes: [5, 14, 22, 23, 26, 27, 31, 32, 33, 34, 35],
        time: 2,
        ing: 2,
        comments: [
            {
                idUser: 0,
                ask: "por que você usou pao integrao ao ines do convencional?",
                answer: "por que eu estou de regime"
            },
            {
                idUser: 0,
                ask: "posso colocar maionese no lugar da manteiga",
                answer: "Não, assim não seria pao com manteiga"
            },
            {
                idUser: 0,
                ask: "essa receita engorda?",
                answer: '',
            }
        ],
        createdAt: new Date(2023, 1, 11, 11,23,10),
    },
    {
        id: 3,
        idUser: 3,
        img: 'https://s2.glbimg.com/WEF_MgZ7NrunOQhc-ZCcEmvwSRQ=/620x620/smart/e.glbimg.com/og/ed/f/original/2022/08/19/5-receitas-mais-buscadas-pelos-brasileiros-pudim-de-leite-em-po.png',
        category: 'Sobremesa',
        name_recipe: 'Pudim que da certo',
        author: 'Rosali de Cassia',
        nmr_hearts: 75,
        nmr_eyes: 117,
        votes: [2,],
        time: 20,
        ing: 5,
        comments: [
            {
                idUser: 0,
                ask: "ele da certo mesmo?",
                answer: "Não sei , mais se quiser testar me conta aqui se deu certo"
            },
            {
                idUser: 0,
                ask: "deu certo mesmo!!!",
                answer: "Serio??"
            },
            {
                idUser: 0,
                ask: "Amei a receita",
                answer: "Obg, peguei no google"
            },
        ],
        createdAt: new Date(2023, 1, 20,14,0,12), 
    },
    {
        id: 4,
        idUser: 4,
        img: 'https://centralblogs.com.br/wp-content/uploads/2019/12/banana-com-chocolate.jpg',
        category: 'Sobremesa',
        name_recipe: 'Sorvete de chocolate',
        author: 'Leticia lopes',
        nmr_hearts: 51,
        nmr_eyes: 91,
        votes: [3, 8, 13, 30],
        time: 30,
        ing: 2,
        comments: [
            {
                idUser: 0,
                ask: "pode ser qualquer chocolate?",
                answer: "sim"
            }
        ],
        createdAt: new Date(2023, 1, 14 , 12, 16, 0)
    },
    {
        id: 5,
        idUser: 0,
        img: 'http://www.hojetemfrango.com.br/wp-content/uploads/2018/12/coxinha-de-frango-especial-seara.jpg',
        category: 'Fast food',
        name_recipe: 'Coxinha com massa de batata',
        author: 'Julia de Carvalho',
        nmr_hearts: 55,
        nmr_eyes: 124,
        votes: [4, 17],
        time: 30,
        ing: 4,
        comments: [],
        createdAt: new Date(2023, 1, 27 ,14,0,12),
    },
    {
        id: 6,
        idUser: 0,
        img: 'https://gastronomiacarioca.zonasul.com.br/wp-content/uploads/2022/03/receitas_chocolate_zona_sul_destaque_gotas_brownie.jpg',
        category: 'Bolos e doces',
        name_recipe: 'Brownlie de chocolate',
        author: 'Julia de Carvalho',
        nmr_hearts: 9,
        nmr_eyes: 19,
        votes: [9, 18, 19],
        time: 45,
        ing: 6,
        comments: [],
        createdAt: new Date(2023, 1, 14, 10, 30, 0),
    },
    {
        id: 7,
        img: 'https://www.receitasagora.com.br/wp-content/uploads/2022/12/brigadeiros-faceis-de-fazer-conheca-essas-receitas-696x464.jpg?ezimgfmt=rs:382x255/rscb1/ngcb1/notWebP',
        category: 'Bolos e doces',
        name_recipe: 'Brigadeiro variado',
        author: 'Rosana de Carvalho',
        nmr_hearts: 7,
        nmr_eyes: 29,
        votes: [10, 11, 20],
        time: 30,
        ing: 4,
        comments: [],
        createdAt: new Date(2023, 1, 23 ,14,0,12),
    },
    {
        id: 8,
        idUser: 0,
        img: 'https://thumbs.dreamstime.com/b/p%C3%A3o-integral-com-maionese-e-margarina-83766779.jpg',
        category: 'Café da manhã',
        name_recipe: 'Pão de forma com maionese',
        author: 'Guilherme Phellippe',
        nmr_hearts: 4,
        nmr_eyes: 11,
        votes: [12, 21, 26],
        time: 2,
        ing: 2,
        comments: [],
        createdAt: new Date(2023, 1, 25,18,52,1),
    },
    {
        id: 9,
        idUser: 0,
        img: 'https://thumbs.dreamstime.com/b/p%C3%A3o-integral-com-maionese-e-margarina-83766779.jpg',
        category: 'Café da manhã',
        name_recipe: 'Pão de forma com queijo',
        author: 'Guilherme Phellippe',
        nmr_hearts: 4,
        nmr_eyes: 11,
        votes: [],
        time: 2,
        ing: 2,
        comments: [],
        createdAt: new Date(2023, 1, 25,18,52,1),
    },
    {
        id: 10,
        idUser: 0,
        img: 'https://thumbs.dreamstime.com/b/p%C3%A3o-integral-com-maionese-e-margarina-83766779.jpg',
        category: 'Café da manhã',
        name_recipe: 'Pão de forma com presunto e raviole',
        author: 'Guilherme Phellippe',
        nmr_hearts: 4,
        nmr_eyes: 11,
        votes: [],
        time: 2,
        ing: 2,
        comments: [],
        createdAt: new Date(2023, 1, 25,18,52,1),
    },
];