export const recipes = [
        {
            id: 0,
            img: 'https://s2.glbimg.com/Lna-moWP46oqPm5QRbzO9imvbDY=/0x0:547x348/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2020/k/u/Fc2LJRT3iDt0m76OI9xg/bolo-de-fuba-cremoso.png',
            category: 'Bolos e doces',
            name_recipe: 'Receita de bolo de fubá cremoso',
            author: 'Julia de Carvalho',
            nmr_hearts: 18,
            nmr_eyes: 98,
            votes: 13,
            time: 45,
            ing: 5,
            createdAt: new Date(2022, 12 , 21),
        },
        {
            id: 1,
            img: 'https://img.itdg.com.br/tdg/images/recipes/000/000/770/323683/323683_original.jpg',
            category: 'Comida caseira',
            name_recipe: 'Arroz soltinho',
            author: 'Caique de Carvalho',
            nmr_hearts: 29,
            nmr_eyes: 53,
            votes: 101,
            time: 15,
            ing: 3,
            createdAt: new Date(2022, 12 , 11),
        },
        {
            id: 2,
            img: 'https://www.padariavicosa.com.br/content/images/thumbs/0000070_pao-com-manteiga-na-canoa_800.jpeg',
            category: 'Café da manhã',
            name_recipe: 'Pão com manteiga',
            author: 'Guilherme Phellipe',
            nmr_hearts: 18,
            nmr_eyes: 67,
            votes: 18,
            time: 2,
            ing: 2,
            createdAt: new Date(2023, 1 , 11),
        },
        {
            id: 3,
            img: 'https://s2.glbimg.com/WEF_MgZ7NrunOQhc-ZCcEmvwSRQ=/620x620/smart/e.glbimg.com/og/ed/f/original/2022/08/19/5-receitas-mais-buscadas-pelos-brasileiros-pudim-de-leite-em-po.png',
            category: 'Sobremesa',
            name_recipe: 'Pudim que da certo',
            author: 'Rosali de Cassia',
            nmr_hearts: 75,
            nmr_eyes: 117,
            votes: 23,
            time: 20,
            ing: 5,
            createdAt: new Date(2023, 1 , 20),
        },
        {
            id: 4,
            img: 'https://centralblogs.com.br/wp-content/uploads/2019/12/banana-com-chocolate.jpg',
            category: 'Sobremesa',
            name_recipe: 'Sorvete de chocolate',
            author: 'Leticia lopes',
            nmr_hearts: 51,
            nmr_eyes: 91,
            votes: 11,
            time: 30,
            ing: 2,
            createdAt: new Date(2021, 1 , 2),
        },
        {
            id: 5,
            img: 'http://www.hojetemfrango.com.br/wp-content/uploads/2018/12/coxinha-de-frango-especial-seara.jpg',
            category: 'Fast food',
            name_recipe: 'Coxinha com massa de batata',
            author: 'Julia de Carvalho',
            nmr_hearts: 55,
            nmr_eyes: 124,
            votes: 21,
            time: 30,
            ing: 4,
            createdAt: new Date(2023, 1 , 27),
        },
        {
            id: 6,
            img: 'https://gastronomiacarioca.zonasul.com.br/wp-content/uploads/2022/03/receitas_chocolate_zona_sul_destaque_gotas_brownie.jpg',
            category: 'Bolos e doces',
            name_recipe: 'Brownlie de chocolate',
            author: 'Julia de Carvalho',
            nmr_hearts: 9,
            nmr_eyes: 19,
            votes: 34,
            time: 45,
            ing: 6,
            createdAt: new Date(2023, 1 , 25),
        },
        {
            id: 7,
            img: 'https://www.receitasagora.com.br/wp-content/uploads/2022/12/brigadeiros-faceis-de-fazer-conheca-essas-receitas-696x464.jpg?ezimgfmt=rs:382x255/rscb1/ngcb1/notWebP',
            category: 'Bolos e doces',
            name_recipe: 'Brigadeiro variado',
            author: 'Rosana de Carvalho',
            nmr_hearts: 7,
            nmr_eyes: 29,
            votes: 37,
            time: 30,
            ing: 4,
            createdAt: new Date(2023, 1 , 23),
        },
        {
            id: 8,
            img: 'https://thumbs.dreamstime.com/b/p%C3%A3o-integral-com-maionese-e-margarina-83766779.jpg',
            category: 'Café da manhã',
            name_recipe: 'Pão de forma com maionese',
            author: 'Guilherme Phellippe',
            nmr_hearts: 4,
            nmr_eyes: 11,
            votes: 33,
            time: 2,
            ing: 2,
            createdAt: new Date(2023, 1 , 25),
        },
];